// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaAzure01.Data;

#nullable disable

namespace ProvaAzure01.Migrations
{
    [DbContext(typeof(MeteoDbContext))]
    [Migration("20250219144224_DbCreationMeteo")]
    partial class DbCreationMeteo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaAzure01.Data.Citta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Citta");
                });

            modelBuilder.Entity("ProvaAzure01.Data.CittaPreferita", b =>
                {
                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<int>("CittaId")
                        .HasColumnType("int");

                    b.HasKey("UtenteId", "CittaId");

                    b.HasIndex("CittaId");

                    b.ToTable("CittaPreferite");
                });

            modelBuilder.Entity("ProvaAzure01.Data.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("ProvaAzure01.Data.CittaPreferita", b =>
                {
                    b.HasOne("ProvaAzure01.Data.Citta", "Citta")
                        .WithMany("CittaPreferite")
                        .HasForeignKey("CittaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvaAzure01.Data.Utente", "Utente")
                        .WithMany("CittaPreferite")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citta");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("ProvaAzure01.Data.Citta", b =>
                {
                    b.Navigation("CittaPreferite");
                });

            modelBuilder.Entity("ProvaAzure01.Data.Utente", b =>
                {
                    b.Navigation("CittaPreferite");
                });
#pragma warning restore 612, 618
        }
    }
}
